apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-demo-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: echo-demo-v1
  template:
    metadata:
      labels:
        run: echo-demo-v1
    spec:
      containers:
      - image: kidlj.com/echo-demo:1.0.0
        imagePullPolicy: IfNotPresent
        name: echo-demo-v1
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: echo-demo-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: echo-demo-v1
  sessionAffinity: None
